# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_report_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='report_period',
            field=models.SmallIntegerField(choices=[(1, 'daily'), (7, 'weekly'), (30, 'monthly')], default=30),
        ),
    ]
