# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180124_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team_access_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
