# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180126_0647'),
        ('accounts', '0009_auto_20180124_1443'),
    ]

    operations = [
    ]
