# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180116_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='often',
            field=models.BooleanField(default=False),
        ),
    ]
