# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180125_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='member_access_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='member_access_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook'), ('hipchat', 'HipChat'), ('slack', 'Slack'), ('pd', 'PagerDuty'), ('po', 'Pushover'), ('victorops', 'VictorOps'), ('sms', 'SMS'), ('twitter', 'Twitter'), ('telegram', 'Telegram')], max_length=20),
        ),
    ]
