# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_check_is_alerted'),
        ('api', '0029_auto_20180125_0918'),
    ]

    operations = [
    ]
