# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180131_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='department',
            new_name='departments',
        ),
    ]
