# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180131_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='departments',
        ),
        migrations.AddField(
            model_name='check',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Department'),
        ),
    ]
