# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180130_1858'),
        ('api', '0030_merge_20180129_1738'),
    ]

    operations = [
    ]
