# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180125_0918'),
        ('api', '0031_auto_20180201_0657'),
    ]

    operations = [
    ]
