# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_merge_20180202_1811'),
        ('api', '0034_merge_20180202_1450'),
    ]

    operations = [
    ]
